//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrypTool.Plugins.ExtrapolateBruteforce.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrypTool.Plugins.ExtrapolateBruteforce.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brute-force metrics.
        /// </summary>
        internal static string _attackerAnalysis {
            get {
                return ResourceManager.GetString("_attackerAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brute-force time: {0}.
        /// </summary>
        internal static string _bruteforceTimeAttackerCaption {
            get {
                return ResourceManager.GetString("_bruteforceTimeAttackerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sophisticated guessing attack time:.
        /// </summary>
        internal static string _bruteforceTimeUserCaption {
            get {
                return ResourceManager.GetString("_bruteforceTimeUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        internal static string _character {
            get {
                return ResourceManager.GetString("_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        internal static string _characters {
            get {
                return ResourceManager.GetString("_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  day.
        /// </summary>
        internal static string _day {
            get {
                return ResourceManager.GetString("_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days.
        /// </summary>
        internal static string _days {
            get {
                return ResourceManager.GetString("_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good entropy value between 60 and 90 reached..
        /// </summary>
        internal static string _entropyGood {
            get {
                return ResourceManager.GetString("_entropyGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entropy is below 40. This could indicate that sophisticated guessing attacks could hash your password earlier than estimated..
        /// </summary>
        internal static string _entropyLow {
            get {
                return ResourceManager.GetString("_entropyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong entropy value between 90 and 120 reached..
        /// </summary>
        internal static string _entropyStrong {
            get {
                return ResourceManager.GetString("_entropyStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very strong entropy of above 120 reached. This is an excellent value..
        /// </summary>
        internal static string _entropyVeryStrong {
            get {
                return ResourceManager.GetString("_entropyVeryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrapolation results.
        /// </summary>
        internal static string _ExtrapolateBruteforce {
            get {
                return ResourceManager.GetString("_ExtrapolateBruteforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 50% of your password got matched. Be aware that sophisticated guessing attacks *could* be successfull earlier because of that..
        /// </summary>
        internal static string _fiftyPercentOfDictionaryMatches {
            get {
                return ResourceManager.GetString("_fiftyPercentOfDictionaryMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; found in &apos;.
        /// </summary>
        internal static string _foundIn {
            get {
                return ResourceManager.GetString("_foundIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guesses: 10 ^ {0}.
        /// </summary>
        internal static string _guessesAttackerCaption {
            get {
                return ResourceManager.GetString("_guessesAttackerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guesses: 10 ^ {0}.
        /// </summary>
        internal static string _guessesUserCaption {
            get {
                return ResourceManager.GetString("_guessesUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hour.
        /// </summary>
        internal static string _hour {
            get {
                return ResourceManager.GetString("_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hours.
        /// </summary>
        internal static string _hours {
            get {
                return ResourceManager.GetString("_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 lowercase letter ({0}%).
        /// </summary>
        internal static string _lowercaseLetter {
            get {
                return ResourceManager.GetString("_lowercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lowercase letters ({1}%).
        /// </summary>
        internal static string _lowercaseLetters {
            get {
                return ResourceManager.GetString("_lowercaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches found:.
        /// </summary>
        internal static string _matchesFound {
            get {
                return ResourceManager.GetString("_matchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% of your password have been found in dictionaries. No matter the security measurements taken, it will be cracked almost instantaneously!.
        /// </summary>
        internal static string _matchesOneHundredPercent {
            get {
                return ResourceManager.GetString("_matchesOneHundredPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} match found:.
        /// </summary>
        internal static string _matchFound {
            get {
                return ResourceManager.GetString("_matchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password reached the minimum amount of characters to pass a standard password policy check. .
        /// </summary>
        internal static string _minimumLengthReached {
            get {
                return ResourceManager.GetString("_minimumLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length of 8 characters surpassed..
        /// </summary>
        internal static string _minimumLengthSurpassed {
            get {
                return ResourceManager.GetString("_minimumLengthSurpassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password reached the minimum length of 12 characters for a nowadays medorately secure password..
        /// </summary>
        internal static string _minimumSecureLengthReached {
            get {
                return ResourceManager.GetString("_minimumSecureLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minute.
        /// </summary>
        internal static string _minute {
            get {
                return ResourceManager.GetString("_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes.
        /// </summary>
        internal static string _minutes {
            get {
                return ResourceManager.GetString("_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        internal static string _moderate {
            get {
                return ResourceManager.GetString("_moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  month.
        /// </summary>
        internal static string _month {
            get {
                return ResourceManager.GetString("_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  months.
        /// </summary>
        internal static string _months {
            get {
                return ResourceManager.GetString("_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lowercase letters.
        /// </summary>
        internal static string _noLowercaseLetters {
            get {
                return ResourceManager.GetString("_noLowercaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dictionary matches found. .
        /// </summary>
        internal static string _noMatchesFound {
            get {
                return ResourceManager.GetString("_noMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No numbers.
        /// </summary>
        internal static string _noNumbers {
            get {
                return ResourceManager.GetString("_noNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No special characters.
        /// </summary>
        internal static string _noSpecialCharacters {
            get {
                return ResourceManager.GetString("_noSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No uppercase letters.
        /// </summary>
        internal static string _noUppercaseLetters {
            get {
                return ResourceManager.GetString("_noUppercaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 number ({0}%).
        /// </summary>
        internal static string _number {
            get {
                return ResourceManager.GetString("_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numbers ({1}%).
        /// </summary>
        internal static string _numbers {
            get {
                return ResourceManager.GetString("_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  over .
        /// </summary>
        internal static string _over {
            get {
                return ResourceManager.GetString("_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches of password: {0}% ({1} {2}).
        /// </summary>
        internal static string _passwordQuotientCaption {
            get {
                return ResourceManager.GetString("_passwordQuotientCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password strength.
        /// </summary>
        internal static string _passwordStrengthCaption {
            get {
                return ResourceManager.GetString("_passwordStrengthCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  second.
        /// </summary>
        internal static string _second {
            get {
                return ResourceManager.GetString("_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seconds.
        /// </summary>
        internal static string _seconds {
            get {
                return ResourceManager.GetString("_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password exceeded the minimum length of 12 characters, which is a must for a nowadays secure password..
        /// </summary>
        internal static string _secureMinimumLengthSurpassed {
            get {
                return ResourceManager.GetString("_secureMinimumLengthSurpassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shannon-Entropy: {0}.
        /// </summary>
        internal static string _shannonEntropyCaption {
            get {
                return ResourceManager.GetString("_shannonEntropyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 special character ({0}%).
        /// </summary>
        internal static string _specialCharacter {
            get {
                return ResourceManager.GetString("_specialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} special characters ({1}%).
        /// </summary>
        internal static string _specialCharacters {
            get {
                return ResourceManager.GetString("_specialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 character.
        /// </summary>
        internal static string _stringLengthOneCharacter {
            get {
                return ResourceManager.GetString("_stringLengthOneCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters.
        /// </summary>
        internal static string _stringLengthOtherThanOne {
            get {
                return ResourceManager.GetString("_stringLengthOtherThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string _strong {
            get {
                return ResourceManager.GetString("_strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password is shorter than 8 characters. Try adding more characters to make it more secure..
        /// </summary>
        internal static string _tooShort {
            get {
                return ResourceManager.GetString("_tooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under .
        /// </summary>
        internal static string _under {
            get {
                return ResourceManager.GetString("_under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 uppercase letter ({0}%).
        /// </summary>
        internal static string _uppercaseLetter {
            get {
                return ResourceManager.GetString("_uppercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} uppercase letters ({1}%).
        /// </summary>
        internal static string _uppercaseLetters {
            get {
                return ResourceManager.GetString("_uppercaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User password string metrics.
        /// </summary>
        internal static string _userAnalysis {
            get {
                return ResourceManager.GetString("_userAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Strong.
        /// </summary>
        internal static string _veryStrong {
            get {
                return ResourceManager.GetString("_veryStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very weak.
        /// </summary>
        internal static string _veryWeak {
            get {
                return ResourceManager.GetString("_veryWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        internal static string _weak {
            get {
                return ResourceManager.GetString("_weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  year.
        /// </summary>
        internal static string _year {
            get {
                return ResourceManager.GetString("_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  years.
        /// </summary>
        internal static string _years {
            get {
                return ResourceManager.GetString("_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zxcvbn-Entropy: {0}.
        /// </summary>
        internal static string _zxcvbnEntropyCaption {
            get {
                return ResourceManager.GetString("_zxcvbnEntropyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured: {0}.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtrapolateBruteforce.
        /// </summary>
        internal static string ExtrapolateBruteforceCaption {
            get {
                return ResourceManager.GetString("ExtrapolateBruteforceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool to evaluate the resistance of passwords against sophisticated guessing and brute-force attacks.
        /// </summary>
        internal static string ExtrapolateBruteforceTooltip {
            get {
                return ResourceManager.GetString("ExtrapolateBruteforceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordCaption {
            get {
                return ResourceManager.GetString("PasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordFeedback.
        /// </summary>
        internal static string PasswordFeedbackCaption {
            get {
                return ResourceManager.GetString("PasswordFeedbackCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathers a detailed report on the password analysis done..
        /// </summary>
        internal static string PasswordFeedbackTooltip {
            get {
                return ResourceManager.GetString("PasswordFeedbackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password.
        /// </summary>
        internal static string PasswordTooltip {
            get {
                return ResourceManager.GetString("PasswordTooltip", resourceCulture);
            }
        }
    }
}
